### ISSUE TITLE
您好，冒昧一问您的本地搜索是如何配置的呢？

### ISSUE THREAD

**Issue by ChenSmallX** [zcgo/tech-blogs.github.io#4]
如题，我用的也是 melody 主题，而且_config.yml 和melody.yml 都像文档里面一样配置好了，但是就是没办法搜索，想参考一下您的配置过程，不知道您方便吗？

**Comment by zcgo** [comment]
这个搜索有问题，结果不是很精确。没有办法搜索是指没有搜索框，还是搜索没结果

**Comment by ChenSmallX** [comment]
search项改为true之后页面有搜索按键，也可以呼出搜索框，但是输入的时候就没有搜索结果。之前的hexo-generate-search的插件也安装了。所以不知道是什么原因。想问一下您的配置环境和配置流程是什么样的

**Comment by ChenSmallX** [comment]
你好，经过查找 melody 的 issue 之后，我解决问题了。问题所在是：

```yml
search:
  path: /search.xml
  field: post
  content: true
```

这里的 path 问题。原来的配置文件默认的设置是 `path:search.xml`，而这是一个相对地址，这样站点无法检索到 search.xml，只有加上了`/`之后就是绝对地址了。
蟹蟹~！
